function dw(message)
{
 if((message.indexOf("<script", 0) != -1) || (message.indexOf("</script", 0) != -1))
 {
  message = message.replace("<script", "&#60script");
  message = message.replace("</script", "&#60/script");  
 }
  
 document.write(message); 
}
function assign_var()
{
			language='English';
show1='首頁';
show2='協助';
show3='登入';
show4='登出';
show5='網路狀態';
show6='連線中';
show7='無連線';
show8='區域網路安裝';
show9='區域網路系統設定';
show10='動態主機組態協定用戶名單';
show11='廣域網路';
show12='連線狀態';
show13='伺服器位址';
show14='媒體存取控制位址';
show15='無線區域網路無法登入';
show16='無線';
show17='Channel and SSID';
show18='安全';
show19='設定為基地台';
show20='選擇IP位址';
show21='媒體存取控制';
show22='無線橋接器';
show23='防火牆';
show24='虛擬伺服器';
show25='用戶端IP過濾功能';
show26='媒體存取控制位址過濾';
show27='非軍事區';
show28='WAN Ping阻擋';
show29='安全記錄';
show30='工具程式';
show31='Parental Control';
show32='重新啟動路由器';
show33='重新啟動基地台';
show34='恢復原廠設定值';
show35='存檔/備用';
show36='恢復之前的設定值';
show37='軔體更新';
show38='系統設定';
show41='DDNS';
show42='Static';
show43='PPPoE';
show44='Dynamic';
show45='PPTP';
show46='Telstra BigPond';
sm1='更多資訊';
btn1='清除更改設定';
btn2='套用更改設定';
btn3='更新網域名稱';
Router='路由器';
AP='基地台';
Dynamic='動態';
cff1='軔體檢查完成';
cff2='軔體資訊';
cff3='無法為此路由器更新軔體';
cff4='無法與軔體資訊伺服器連線，請確認無線區域網路已連線';
			d1='重複的管理者登入';
			d2='Belkin | 重複的管理者登入';
			d3='此裝置由xxx管理';
			d4='現在!!';
			fc1='防火牆 > 用戶IP過濾 ';
			fc2a='此路由器可被設定為在特定日期與時間只存取網路、電子郵件或其他網路服務'; fc2b=' ';			
			IP='網際網路協定';
			Port='連接埠';
			Type='類型';
			BT='阻擋時間';
			Day='日期';
			Tm='時間';
			Enable='開啟';
			BOTH='兩者皆用';
			Always='永遠啟用';
			Block='阻擋';
			SUN= '>星期天';
			MON= '>星期一';
			TUE= '>星期二';
			WED= '>星期三';
			THU= '>星期四';
			FRI= '>星期五';
			SAT= '>星期六';
			PM= ':00 中午';
			AM= ':00 晚上';
			
	fcipm='您可能尚未登入用戶IP位址或您所輸入的部份IP位址是不正確的。IP位址可為介於0至255之間的任一數字';
	fcsm='您所輸入的通訊埠號碼是不正確的';
	fcrm='後者連接埠範圍應大於前者';
	fcripm='後者IP範圍應大於前者';
	fcpm='在此欄位中的數字應介於1到65535';
　　fd1='防火牆 > 非軍事區';
	fd2='非軍事區功能能讓您指定特定任一在您區域中的電腦被網路位址防火牆取代。如果網路位址發生問題，這項功能是必需的，由其當您使用電腦遊戲或是視訊會議時。若臨時狀況發生請使用此項功能。';
	fd3='在此非軍事區的電腦並未受到駭客侵襲的保護';
	fd4='請輸入IP位址的最後一位數字並選取『啟用』。點選『Summit』使更改生效。';
	fd5='虛擬非軍事區主機IP位址';
	fd6='靜態IP';  fd7='私人IP';  fd8='啟用';
	fd9='防火牆 > DDNS'; 
	fd10='請在啟用非軍事區前輸入IP位址';		
　　fd11='請至少輸入一個IP位址 &nbsp;';　　		
　　fd12='ユーザ名 > '; 
　　fd13='パスワード > '; 
　　fd14='ドメイン名 > ';
	fd15='請在啟用非軍事區前輸入IP位址'; 
fd16='自動更新'; 
　　fmc1='防火牆 > 媒體存取控制位址過濾';
　　fmc2='此項功能能讓您設定準許用戶清單。當您啟用此項功能，您必須在您的網絡中輸入每一位使用者的媒體存取控制位址，這樣每一位使用者才能存取網絡中的資料';
　　fmc3='啟用媒體存取控制位址過濾';
　　fmc4='媒體存取控制位址過濾清單';
　　fmc5='阻擋';
　　fmc6='主機';
　　fmc7='媒體存取控制位址';
　　fmc9='無法輸入多重播送媒體存取控制位址';
	fmc12='此媒體存取控制位址已被加入';
	Add='加入'; 
　　Del='刪除';
　　fmcipm='您可能未輸入全部的十六進位數字或是部份您所輸入的十六進位數字是不正確的。一個十六進位數字應為0至9或是A至F的字母';
　　fmn1='防火牆 >';
　　fmn2='您的路由器有一個可以保護您的網路被一般駭客入侵，包括Ping of Death(PoD)和Denial of Service (DoS)。如果需要的話您可以將防火牆關閉。雖然說將防火牆關閉不會讓您完全無法阻擋駭客的攻擊，但還是建議您盡量都開啟防火牆'; 
　　fmn3='防火牆啟用/關閉 >';
	Disable='關閉 ';
	fp1='Firewall > 阻擋WAN Ping';
　　fp2='<b>進階設定功能</b> 您可以設定不回應ICMP Ping(ping to the WAN連接埠)。這可以提高安全度'; 
　　fp3='阻擋ICMP Ping >';  
	fs1='防火牆 > 安全記錄';
　　fs2='此路由器保存所有登入與登出之記錄，以及所有網路上的攻擊，記錄可在下方查閱'; 
　　fs3='記錄檔案';
　　Save='存檔';
　　Clear='清除';
　　Refresh='重新整理';  
	fv1='防火牆 > 虛擬伺服器';
　　fvipm='您可能尚未輸入所有IP位址，\n或是部份您所輸入的數字是不正確的。\nIP位址的數字應介於0至255之間。';
　　fvrm='此公用連接埠號碼不可能是88，因為與無線路由器網路服務相衝';
　　fvipr='內傳連接埠範圍不正確';
　　fvppr='私人連接埠範圍不正確';
			fv1='Firewall > Virtual servers';
　　fv2='這項功能能夠讓您追蹤外部(網際網路)的服務連線，例如網路伺服器(連接埠80)，FTP伺服器(連接埠21)或其他應用程式藉由路由器到達您內部網絡的其他程式';			fv3='Active Worlds';
			fv4='Age of Empires';
			fv5='Age of Empires Expansion: The Rise of Rome';
			fv6='Age of Empires II Expansion: The Conquerors';
			fv7='Age of Empires II: The Age of Kings';
			fv8='Age of Kings';
			fv9='Age of Wonders';
			fv10='Aliens vs. Predator';
			fv11='Anarchy Online(BETA)';
			fv12='AOL Instant Messenger';
			fv13='Audiogalaxy Satellite';
			fv14='Baldur Gate';
			fv15='BattleCom';
			fv16='Battlefield Communicator';
			fv17='Black and White';
			fv18='Blizzard Battle.net';
			fv19='Buddy Phone';
			fv20='Bungie.net';
			fv21='Camerades';
			fv22='CART Precision Racing';
			fv23='Close Combat for Windows';
			fv24='Close Combat III: The Russian Front';
			fv25='Close Combat: A Bridge Too Far';
			fv26='Combat Flight Simulator 2: WWII Pacific Theater';
			fv27='Combat Flight Simulator: WWII Europe Series';
			fv28='Crimson Skies';
			fv29='Dark Reign';
			fv30='Dark Reign 2';
			fv31='Delta Force 2';
			fv32='Delta Three PC to Phone';
			fv33='Descent 3';
			fv34='Descent Freespace';
			fv35='Diablo (1.07+)';
			fv36='Diablo I';
			fv37='Diablo II';
			fv38='DialPad.Com';
			fv39='DirectX 7遊戲';
　			fv40='DirectX 8遊戲';
　			fv41='伺服器位址';
			fv42='Doom';
			fv43='Dune 2000';
			fv44='Dwyco Video Conferencing';
			fv45='Elite Force';
			fv46='Everquest';
			fv47='F-16';
			fv48='F-22 Lightning 3';
			fv49='F-22 Raptor';
			fv50='F22 Raptor (Novalogic)';
			fv51='Falcon 4.0';
			fv52='Fighter Ace II';
			fv53='Flight Simulator 2000';
			fv54='Flight Simulator 98';
			fv55='Freetel';
			fv56='FTP伺服器';
			fv57='GNUtella';
			fv58='Golf 1998 Edition';
			fv59='Golf 1999 Edition';
			fv60='Golf 2001 Edition';
			fv61='Go2Call';
			fv62='Half Life';
			fv63='Half Life Server';
			fv64='Heretic II Server';
			fv65='I76';
			fv66='Ivisit';
			fv67='IRC';
			fv68='IStreamVideo2HPz';
			fv69='KaZaA';
			fv70='Kohan Immortal Sovereigns';
			fv71='LapLink Gold';
			fv72='Links 2001';
			fv73='Lotus Notes伺服器';
			fv74='Mail (POP3)';
　　		fv75='Mail (SMTP)';
			fv76='MechCommander 2.0';
			fv77='MechWarrior 3';
			fv78='MechWarrior 4';
			fv79='Media Player 7';
			fv80='Midtown Madness';
			fv81='Midtown Madness 2';
			fv82='Mig 29';
			fv83='Monster Truck Madness';
			fv84='Monster Truck Madness 2';
			fv85='Motocross Madness';
			fv86='Motocross Madness 2';
			fv87='Motorhead Server';
			fv88='MSN Gaming Zone';
			fv89='MSN遊戲區';
			fv90='Myth';
			fv91='Myth II Server';
			fv92='Myth: The Fallen Lords';
			fv93='Need for Speed';
			fv94='NetMech';
			fv95='NTP(Network Time Protocol )';
			fv96='News Server (NNTP)';
			fv97='OKWeb';
			fv98='OKWin';
			fv99='Outlaws';
			fv100='pcAnywhere v7.5';
			fv101='PhoneFree';
			fv102='Polycom ViaVideo H.323';
			fv103='Polycom ViaVideo H.324';
			fv104='Quake';
			fv105='Quake II (Client and Server)';
			fv106='Quake III';
			fv107='Red Alert';
			fv108='Rise of Rome';
			fv109='Roger Wilco';
			fv110='Rogue Spear';
			fv111='Secure Shell Server (SSH)'; 
　　		fv112='Secure Web Server (HTTPS)'; 
			fv113='ShoutCast';
			fv114='SNMP';
			fv115='SNMP Trap';
			fv116='Speak Freely';
			fv117='StarCraft';
			fv118='Starfleet Command';
			fv119='StarLancer';
			fv120='SWAT3';
			fv121='Telnet Server';
			fv122='The 4th Coming';
			fv123='Tiberian Sun: C&C';
			fv124='Tiberian Sun: C&C III';
			fv125='Total Annihilation';
			fv126='Ultima';
			fv127='Unreal Tournament';
			fv128='Urban Assault';
			fv129='VoxPhone 3.0';
			fv130='Warbirds 2';
			fv131='Web Server (HTTP)'; 
			fv132='WebPhone 3.0';
			fv133='Windows 2000 Terminal Server';
			fv134='X Windows';
			fv135='Yahoo Pager';
			fv136='Yahoo即時通訊';
			fv137='Pal Talk';
			fv138='Real Player 8 Plus';
			fv139='RealAudio';
			fv140='Netmeeting 2.0, 3.0, Intel Video Phone';
			fv141='Westwood Online';
			fv142='CuSeeMe';
			fv143='ICUII Client';
			fv200='清除記錄';	
			Description='說明';  
			Inb='內傳連接埠';  
			Type='類型';  
			Pipa='私人IP位址';  
			Pport='私人連接埠';  
			htop='回到最前面'; 
h1='協助';
h2='名詞解釋';
h3='<b>管理員</b> 管理員可提供網路維護服務。對此路由器而言，管理者可更改路由器設定。';
h4='<b>用戶</b> 指在此網路上之電腦，其可使用路由器所提供的功能，例如自動DHCP伺服器及防火牆。';
h5='<b>主機通訊協定組態</b> 主機通訊協定組態‧此通訊協定可自動將每一台電腦中的TCP/IP組態。';
h6='<b>撥號連線</b> 使用公用電話網路連接。';
h7='<b>非軍事區</b> 路由器中的虛擬區域並不受到路由器防火牆的保護。在同一時間內，只有一台電腦可以放在非軍事區中。';
h8='<b>網域名稱系統伺服器位址</b> DNS意指網域名稱系統，可使網路電腦主機享有一網域名稱(例如:belkin.com)以及一個或更多IP位址(例如:192.34.45.8)。一個DNS伺服器可保有主機電腦的資料庫, 網域名稱及IP位址，故當您需要一個網域名稱時，使用者可以得到一個正確的IP位址。家用網路的電腦所使用之DNS伺服器位址位於您網際網路服務供應商所指定的DNS伺服器。';
h9='<b>數位用戶專線數據機</b>  DSL意指數位用戶專線，一個DSL數據機是用您現有的電話線以高速來傳送資料。';
h10='<b>動態IP</b>  即指一個自動由DHCP伺服器上獲得的IP位址。';
h11='<b>乙太網路</b> 這是電腦網路使用的標準 乙太網路是透過訊號線和特殊集線器進行連接，傳送資料的速度可高達每秒1000萬bits。';
h12='<b>防火牆</b> 防火牆意指一道電子牆，可以阻擋未經授權的使用者存取特定檔案或在網絡中的電腦。';
h13='<b>軔體</b> 意指安裝在記憶體中的軟體。必要的程式將會持續運作儘管系統已經關閉。軔體比硬體容易更動但比儲存在磁片上的軟體來得穩定。';
h14='<b>IP位址</b> 意指網際網路協定  一個IP位址是由四組以句點分開的數字所組成，可用來標示一個網際網路的電腦主機，例如:192.34.45.8。';
h15='<b>整體服務數位網路</b>  數位傳輸線可以同時傳送聲音、影像等資訊高達128K，比一般高速類比訊號數據機的更快更穩定。許多電信公司都提供ISDN傳輸線。';
h16='<b>網際網路服務供應商</b> ISP就是可以讓個人、企業或組織連接到網際網路的公司。';
h17='<b>ISP閘道位址</b> (參照ISP說明) ISP閘道位置是給網際網路路由器的IP位址，只有在使用有線或DSL數據機時，才需要使用這個位址。';
h18='<b>區域網路</b> LAN就是一群在相對而言較小的區域內(例如:家裡或辦公室內)相互連接在一起的電腦和裝置。您家中的網路就是一個LAN。';
h19='<b>MAC位址</b> MAC意指媒體存取控制。媒體存取控制位址就是連接到網路之裝置的硬體位址。';
h20='<b>MTU</b> 指最大傳輸單元  即每次傳輸資料的最大值。';
h21='<b>網路位置轉換</b>  此流程可讓您家中的所有電腦共享一個IP位址，這樣您就可以透過家中網路的任何一部電腦存取網際網路上的資料，而無需向ISP購買其他的IP位址。';
h22='<b>連接埠</b> 一個特定的頻道是介由特定的連接埠號碼所定義。';
h23='<b>乙太網路使用的點對電協定</b>  點對點協定是一種安全的資料傳輸方法，最早是用於撥接連線。PPPoE是用於乙太網路。';
h24='<b>點對點通訊協定</b>  它是PPP(點對點通訊協定)的一種，可以將一個通訊協定壓縮的許多檔案並且讓另一個通訊協定使用。這種通訊科技可讓TCP/IP資料在非TCP/IP網絡上傳輸。PPTP可讓您利用網路當成媒介去加入不同的網絡。';
h25='<b>簡易網路時間通訊協定</b>  可以讓您的路由器與系統的時間顯示一致。';
h26='<b>動態封包狀態偵測</b>  SPI防火牆是一種由您家用的網絡閘道提供的企業用戶級網路安全保護。使用SPI，閘道即可像防火牆一樣保護您的網絡不受駭客侵襲。';
h27='<b>靜態IP</b> 意指由手動組態且不會改變的IP。';
h28='<b>子網路遮罩</b> 子網路遮罩可為您的網際網路服務供應商所提供的資訊，是由四組很類似IP位址的數字所組成。用來建立使用在特定網絡的IP位址(相反於可被網路辨識的IP位址，其必需被Inter電腦網路介面卡指定。';
h29='<b>傳輸控制協定</b> 這是最常被使用的傳輸協定 TCP是連線性與不中斷性，故其可以提供穩定的傳輸與';
h30='<b>傳輸控制協定/網際網路協定</b> 這是透過網路資料傳輸的標準';
h31='<b>網路終端機協定</b> 網際網絡的通訊協定、從一台電腦傳送一個終端機訊息到另外一台正在運作應用程式的電腦。不像是TCP，UDP是透過無線傳輸模式而能保證絕對穩定的傳輸，這個應用程式本身必須偵測所有錯誤並檢查可靠的傳送';
h32='<b>廣域網路</b>  一系列彼此相連的LAN，連接許多位於不同地點(例如:不同建築物、城市、國家)網際網路就是一個廣域網路';
h33='<b>廣域網路</b>IP位址 此IP位址由ISP的路由器指定';
h34='<b>無線區域網路</b>  一個透過無線的方式連接許多電腦的區域網路';

Enabled='啟用';
Disabled='關閉';
i1='設定首頁';
i2='狀態';
i3='版本資訊';
i4='軔體版本';
i5='創始版';
i6='硬體';
i7='序號';
i8='區域網路設定';
i9='區域網路/無線區域網路 媒體存取控制';
i9a='區域網路 媒體存取控制';
i9b='無線區域網路無法連線';
i10='IP位址';
i11='子網路遮罩';
i12='DHCP伺服器';
i13='網際網路設定';
i14='廣域網路\n媒體存取控制設定';
i15='連線類型';
i16='子網路遮罩';
i17='Wan IP';
i18='設定值閘道';
i19='DNS位址';
i20='特性';
i21='網路位址轉換';
i22='防火牆設定';
i23='SSID';
i24='安全';
i25='印表機';
i26=' (啟用/關閉) ';
i27='在更動任何設定前，您必須先登入';
i28='印表機伺服器/印表機';
i29='印表機伺服器名稱';
i30='FTP列印';
i31='RAW TCP/IP列印'; 
i32='WLAN 設定';
i33='UPnP';
i34='WLAN MAC';
i35='系統時間';
langt='語言';
langc='繁體中文';
ld1='區域網路 > DHCP';
ld2='區域網路 > DHCP用戶名單';
ld3='此頁顯示您網絡中每一台電腦的IP位址、主機名稱與媒體存取控制位址。如果電腦沒有特定的主機名稱，可將主機名稱欄位留白。請按"重新整理"來重新整理清單'; 
ld4='IP位址'; 
ld5='主機名稱';
ld6='媒體存取控制位址';		
lm1='區域網路';
lm2='您的路由器是由動態主機組態協定指定您網絡中每一台電腦的IP位址，DHCP伺服器運作時大部份時間會使用原廠設定值，若您需要更動，可以隨時更改'; 
lm3='您所能更改的設定為: ';
lm4='- 更改路由器的IP位址，預設值為192.168.2.1';
lm5='- 更改子網路遮罩位址，預設值為255.255.255.0';
lm6='- 開啟/關閉DHCP伺服器功能，預設值為開啟';
lm7='- 指定開始與末尾IP位址清單。開始預設值為2，末端為100';
lm8='- 指定一個IP位址租賃時間';
lm9='- 指定一個當地的網域名稱';
lm10='若需更改設定，請選在左邊LAN tab鍵的LAN Settings';
lm11='路由器提出您一個能連接到電腦的用戶清單。要檢視此清單，請按LAN鍵旁的\"DHCP用戶清單\"';
ls1='區域網路 > 區域網路設定';
ls2='您可以在此更改區域網路的設定。若要更改生效，請選取\"套用變更\"';
ls3='IP位址';
ls4='子網路遮罩';
ls5='DHCP伺服器';
On='開啟';  
Off='關閉'; 
all='all';
Auto='Auto'; 
langt='語言'
langc='繁體中文'
langcl='現在使用的語言';
langal='可用的語言';
ls6='DHCP伺服器能簡易地透過指定網絡中的每台電腦一個IP位址';
ls7='IP位址開始數字';
ls8='IP位址結束數字';
ls9='租賃時間';
ls10='永遠';
ls11='半小時';
ls12='一小時';
ls13='兩小時';
ls14='半天';
ls15='一天';
ls16='兩天';
ls17='一週';
ls18='兩週';
ls19='DHCP伺服器能夠為每台電腦在特定的時間內預留特定的IP位址';  
ls20='區域名稱';
Optional='選用項目';    
ls21='讓您為您的網絡命名'; 
lsipm='您可能未輸入所有的號碼或是您所輸入的部份號碼是不正確的。此欄位中的號碼應介於0和255';			
lssm='您所輸入的子網路遮罩名稱是不正確的';
lsnetm='IP位址值應與IP閘道位址一樣位於一樣的子網路中';
lsendm='最後的IP位址必須大於開始的IP位址';
lspoolm='區域網路的IP位址不能來自於DHCP位址的清單'; 
lsipm2='不正確的IP位址，最後一個數字不可為0或255';		
lsipm3='不正確的IP位址，最後一個數字不可為127或0';
lsldnm='不正確的網域名稱';
lsipm4='您所輸入的IP名稱是不正確的';
lsipalert='請手動更改瀏覽器中的狀態';
lsipm5='您所選的IP位址應為non-routable，IP.\n  192.168.x.x (x可以介於0和255.) \n10.x.x.x (x可以介於0和255.)\n172.y.x.x (y可為介於16和31的任何數字, 而且x 可介於0和255.)';
lsipc='您確定要更改區域網路的IP位址嗎? ';
lo1='登入';
lo2='在您做出任何更改前，您需要用一個密碼登入。如果您尚未設定您個人的密碼，請將此欄留白然後選取';
lo3='密碼';  
lo4='預設值 = 留白';
Clear='清除';
Submit='傳送';
le1='Belkin | 登入錯誤';
lerror='登入錯誤!!';  

Utilities='工具程式 > ';
rs1='重新啟定成功 ';
rs2='當電源燈停止閃爍時表示重新啟動已完成';  
rs3='路由器正重新啟動中';
rs4='所剩秒數';  

rf1='恢復設定值成功'; 
rf2='當電源燈停止閃爍時表示恢復已完成';  

rss1='恢復設定成功 ';
rss2='當電源燈停止閃爍時表示恢復設定已完成';  

ufy1='恢復系統設定值';
ufy2='使用此選項可以將所有設定恢復為原廠設定值。我們建議您在恢復所有預設值前，請先儲存您的設定值。若要恢復原廠設定值，請按下方的\"恢復預設值\"鍵';
			ufy3='警告: 您所有的設定都會消失，您確定要繼續嗎?';
ufy4='恢復預設值需要六十秒的時間。請不要在過程中關閉電源 ';
ufy5='將不會恢復原廠預設值。沒有任何設定會消失。';
ufy='恢復預設值';
			
ufe1='軔體更新';
ufe2='有時貝爾金會發行新版本的軔體。更新版的軔體包含了可以修改現有問題的資訊。請按下方按鍵檢視是否有新的軔體更新版本';
ufe3='注意: 在更新軔體版本前，請先儲存您現在的設定';
ufe4='請按此';
ufe5='到這裡儲存/備用現在的設定';
ufe6='按此獲得新軔體版本 >';
ufe7='確認軔體'; 
ufe8='更新軔體 >';
Update='更新';
ufe9='請指定更新檔案的位置。請輸入檔案路徑和檔案名稱。按\"瀏覽\"來尋找檔案位置';
ufe10='您確定您要繼續更新嗎? ';
ufe11='在升級的最後，路由器大約在一分鐘內暫時不會有回應。這是很正常的現象，請不要關閉電源或重新啟動';
			
um1='這個螢幕能讓您使得不同的參數與特定的管理功能運作';
um2='個人控制台';
um3='貝爾金的Parental Control能保護您和您的孩子遠離不適當的網路內容'; 
um4='貝爾金的Parental Control是您所來設定的過濾網。現在您可以和您的孩子一同瀏覽網路，您不在時也可放心讓孩子瀏覽<br>&nbsp;';

um5='重新啟動路由器';
um6='有時後不一定需要重新啟動路由器。當路由器開始不正常運作時，重新啟動不會刪除任何您的組態設定'; 
um7='恢復原廠設定值';
um8='選用此選項能讓您將所有設定恢復為原廠設定值。我們建議您先備份您的設定再恢復所有預設值';
um9='儲存/備份現在設定';
um10='您可使用此功能儲存您目前的組態設定。儲存您的組態設定可以讓您在稍後更改或不小心遺失時恢復。我們建議您在軔體更新前先備份您的組態設定';
um11='恢復先前儲存設定';
um12='此選項能讓您恢復先前所儲存的組態設定';
um13='軔體更新';
um14='有時貝爾金會發行新版本的軔體。更新版的軔體包含了可以修改現有問題的資訊。';
um15='系統設定';
um16='您可以在系統設定頁面設定管理者密碼';
um17='設定時區，開啟遠端管理並開啟或關閉NAT功能';
um18=' of the';			
upc1='工具程式 > Parental Control';
upc2='貝爾金Parental Control保護您和您的孩子與員工遠離不適當的網路內容。Parental Control可以預先組態並阻擋不適當的內容。您可以輕易地選擇將任何網站永遠阻擋或是永遠允許';
upc3='您現在Parental Control訂購狀況為 ';
upc4='未啟用'; 
upc5='無法啟用';
upc6='啟用';
upc7='請按此停止登入:';
upc8='過期';
upc9='您的訂購將在XXX到期';
days='天數';
upc10='帳號資料';
Advanced='進階';
Apply='應用';
upc11='重新整理帳戶資訊';
upc12='回報';
upc13='您現在';
upc14=' subscribed to reporting.';
not='not';
upc15='按此檢視回報樣本';
upc16='回報樣本';
upc17='按此申請回報樣本';
upc18='現在訂購';
upc19='按此觀看您的回報';
upc20='檢視回報';
upc21='Parental Control狀態';
upc22='將Parental Control過濾開啟或關閉';
upc23='網路防火牆現在正';
ON='開啟';
OFF='關閉';
pwd='密碼';
upc24='電子郵件提醒';
upc25='如果個人控制台無效請以電子郵件通知我';
upc26='電子郵件現在正';
upc27='修改規定';
upc28='觀看您Parental Control設定值的XX，請按此';
Modify='修改';
upc29=' Parental Control申請';
upc30='貝爾金的個人控制台能保護您和您的孩子遠離網路上不佳的內容。貝爾金個人控制台是由您所設定的防火牆，現在您可以隨意瀏覽網路，甚至不需擔心您的孩子單獨瀏覽'; 
upc31='您現在並無訂購Parental Control服務';  
upc32='更新Parental Control';
upc33='您的訂閱即將過期。請按此更新您的訂購';
upc34='馬上更新';
upc35=' URL是空白的';
upa1=' Parental Control帳戶資訊';
upa2='您可以更改Parental Control用戶資訊例如: Parental Control提示電子郵件與Parental Control管理員密碼';
upa3='更改 Parental Control提示電子信箱地址';
upa4='您現在使用的電子郵件信箱'; 
upa5='輸入您新的電子郵件信箱'; 
upa6='再次確認您的新的電子郵件信箱';
upa7='更改您個人控制台的管理員密碼';
upa8='輸入您的新密碼';
upa9='再次輸入您的新密碼';
upa14='電子郵件信箱無效';
Change='更改';
Stop='應用';		
upad1='個人控制台進階設定值無效';
upad2=" Belkin Parental Control需要Cerberian(我們的夥伴)網路瀏覽人數計數器。在一般的狀況之下，回應時間會少於一秒，所以不會有延遲。然而，當您向Cerberian要求一個很少人瀏覽的網頁時，他們會不斷更新計數器，這可能會花數秒的時間，取決於網站下載的時間。";
Timeout='超過時間';
upad3='超過等候時間';
upad4='需數秒等待回應';
upad5='Default behavior when timeout occurs';
upad6='設定當超過登入時間預設值，路由器會根據此設定阻擋或允許所有瀏覽的網頁';
upad7='准許所有網頁超過時間';
upad8='阻擋所有網頁超過時間';
upr1='工具程式 > Parental Control帳戶更新';
upr2='當您的PARENTAL CONTROL訂購功能不正確時，您才需要此功能。<br>請按下此鍵，路由器將會下載或重新整理所有貝爾金帳戶資訊。<br>欲重新整理您的PARENTAL CONTROL路由器帳戶資訊，請按\"重新整理\" ';
uprev1='工具設定 > 恢復之前儲存的設定';
uprev2='這個選擇能讓您恢復之前儲存的組態';  
Restore='恢復';
uprev3='輸入含有備份設定的檔案名稱';
uprev4='您要繼續恢復設定嗎? ';
uprev5='在恢復設定後，路由器可能在一分鐘內暫時不會有回應，這是很正常的現象，請勿關閉路由器電源';
ur1='工具設定 > 恢復路由器 ';
ur2='當路由器開始不正常運作時，有時候您可能必須重新啟動路由器。重新啟動並不會使您的組態設定值消失，請按下方按鍵重新啟動';
ur3='重新啟動';
ur4='您確定要重新啟動嗎? 重新啟動不會影響您的電腦組態';
ur5='路由器需要六十秒的時間重新啟動。在重新啟動完成前請勿將電源關閉';
usave1='儲存/備用現在的使用值';
usave2='您可以現在儲存您的設定'; 
Save='儲存';
usys1='工具設定 > 系統設定';
usys2='管理者密碼: '; 
usys3='此路由器並未設定任何密碼，為了確保安全，您可以在此設定一組密碼';
usys4='輸入現在使用的密碼';
usys5='輸入新的密碼';  
usys6='確認新的密碼';  
usys7='超過登入時間';
usys8='1-99分鐘'; 
usys9='時間與時區'; 
January='一月'; 
February='二月'; 
March='三月'; 
April='四月'; 
May='五月'; 
June='六月'; 
July='七月'; 
August='八月'; 
September='九月'; 
October='十月'; 
November='十一月'; 
December='十二月';
usys10='請設定您所在的時區。如果您在節約日光區(指在夏季把標準時間撥早1小時的區域)，請按此處';
usys11='時區';
usys12='(GMT-12:00) 瓜加林島'; 
usys12='(GMT-12:00) 瓜加林島'; //(GMT-12:00) Enewetak, Kwajalein 
usys13='(GMT-11:00) 薩摩亞'; //(GMT-11:00) Midway Island, Samoa 
usys14='(GMT-10:00) 夏威夷'; // Hawaii 
usys15='(GMT-09:00) 美國阿拉斯加州'; // Alaska 
usys16='(GMT-08:00) 太平洋時區(美國與加拿大) '; // Pacific Time (US & Canada); Tijuana 
usys17='(GMT-07:00) 美國亞歷桑那州'; // Arizona 
usys18='(GMT-07:00) 美國與加拿大山區'; // Mountain Time (US & Canada)
usys19='(GMT-06:00) 美國與加拿大中部'; // Central Time (US & Canada)
usys20='(GMT-06:00) 美國與加拿大中部'; //Mexico City, Tegucigalpa
usys21='(GMT-06:00) 薩克斯其萬省'; //Saskatchewan
usys22='(GMT-05:00) 利馬(秘魯首都) '; // Bogota, Lima, Quito 
usys23='(GMT-05:00) 美國與加拿大東部'; // Eastern Time (US & Canada)
usys24='(GMT-05:00) 美國印第安納州'; // Indiana (East)
usys25='(GMT-04:00) 大西洋(加拿大)'; // Atlantic Time (Canada)
usys26='(GMT-04:00) 卡拉卡斯(委内瑞拉首都)，拉巴斯(玻利維亞之首都) '; // Caracas, La Paz 
usys27='(GMT-04:00) 聖地亞哥(智利首都) '; //Santiago 
usys28='(GMT-03:00) 紐芬蘭(加拿大東海岸的島嶼) '; // Newfoundland 
usys29='(GMT-03:00) 巴西'; // Brasilia 
usys30='(GMT-03:00) 布宜諾斯艾利斯(阿根廷首都)，喬治城(南美蓋亞那共和國首都)'; // Buenos Aires, Georgetown 
usys31='(GMT-02:00) 大西洋中部'; // Mid-Atlantic 
usys32='(GMT-01:00) 亞速爾群島'; // Azores, Cape Verde Is.
usys33='(GMT) 卡薩布蘭卡市(摩洛哥海濱)，蒙羅維亞(賴比瑞亞首都) '; // Casablanca, Monrovia 
usys34='(GMT) 格林威治時間：都伯林、愛丁堡'; // Greenwich Mean Time: Dublin, Edinburgh 
usys35='(GMT) 格林威治時間：里斯本、倫敦'; // Greenwich Mean Time: Lisbon, London 
usys36='(GMT+01:00) 阿姆斯特丹、柏林、伯恩、羅馬'; // Amsterdam, Berlin, Bern, Rome 
usys37='(GMT+01:00) 斯德哥爾摩、維也納、貝爾格勒(南斯拉夫首都) '; // Stockholm, Vienna, Belgrade 
usys38='(GMT+01:00) 伯拉第斯拉瓦(捷克)、布達佩斯(匈牙利首都)、盧布爾雅那(斯洛維尼亞共和國首都)'; // Bratislava, Budapest, Ljubljana 
usys39='(GMT+01:00) 布拉格、布魯塞、哥本哈根、馬德里'; // Prague,Brussels, Copenhagen, Madrid 
usys40='(GMT+01:00) 巴黎、維爾紐斯(立陶宛共和國首都)、塞拉耶佛(玻茲尼亞澤哥維那共和國首都)、史可普列(馬其頓共和國首都)'; // Paris, Vilnius, Sarajevo, Skopje 
usys41='(GMT+01:00) 華沙(波蘭首都)、札格拉布(克羅埃西亞共和國首都) '; // Sofija, Warsaw, Zagreb 
usys42='(GMT+02:00) 雅典、伊斯坦堡、明斯克(白俄羅斯首都) '; // Athens, Istanbul, Minsk 
usys43='(GMT+02:00) 布加勒斯特(羅馬尼亞首都) '; // Bucharest 
usys44='(GMT+02:00) 開羅'; // Cairo 
usys45='(GMT+02:00) 普利托里亞(南非行政首都) '; // Harare, Pretoria 
usys46='(GMT+02:00) 赫爾辛基、里加(拉脱維亞共和國首都)、 塔林(愛沙尼亞共和國首都) '; // Helsinki, Riga, Tallinn 
usys47='(GMT+02:00) 以色列'; // Israel 
usys48='(GMT+03:00) 巴格達(伊拉克首都)、科威特、奈洛比(肯亞共和國首都)、利雅德(沙特阿拉伯) '; // Baghdad, Kuwait, Nairobi, Riyadh 
usys49='(GMT+03:00) 莫斯科(俄羅斯首都) '; // Moscow, St. Petersburg 
usys50='(GMT+03:00) 德黑蘭(伊朗首都) '; // Tehran 
usys51='(GMT+04:00) 阿布達比(阿拉伯聯合大公國之首都)、馬斯喀特(阿曼首都)、第比利斯(格魯吉亞共和國首都) '; // Abu Dhabi, Muscat, Tbilisi, Kazan 
usys52='(GMT+04:00) 喀布爾(阿富汗首都) '; // Volgograd, Kabul 
usys53='(GMT+05:00) 伊斯蘭馬巴德(巴基斯坦首都)、喀拉蚩港市(巴基斯坦) '; // Islamabad, Karachi, Ekaterinburg 
usys54='(GMT+06:00) 達卡(孟加拉首都) '; // Almaty, Dhaka 
usys55='(GMT+07:00) 曼谷、雅加達、河內'; // Bangkok, Jakarta, Hanoi 
usys56='(GMT+08:00) 北京、重慶、烏魯木齊'; //Beijing, Chongqing, Urumqi
usys57='(GMT+08:00) 香港、柏斯、新加坡、台北'; // Hong Kong, Perth, Singapore, Taipei 
usys58='(GMT+09:00) 東京、大阪、札幌、亞庫次克'; // Toyko, Osaka, Sapporo, Yakutsk 
usys59='(GMT+10:00) 布里斯本'; // Brisbane 
usys60='(GMT+10:00) 坎培拉、墨爾本、雪梨'; // Canberra, Melbourne, Sydney 
usys61='(GMT+10:00) 關島、摩爾斯比港(巴布亞新幾內亞之首都)、海參崴'; // Guam, Port Moresby, Vladivostok 
usys62='(GMT+10:00) 哈伯特'; //Hobart
usys63='(GMT+11:00) 馬喀丹州(俄羅斯)、新喀里多尼亞'; // Magadan, Solamon, New Caledonia 
usys64='(GMT+12:00) 斐濟、堪察加半島(西伯利亞)'; // Fiji, Kamchatka, Marshall Is.
usys65='(GMT+12:00) 威靈頓、奥克蘭'; // Wellington, Auckland			
usys66='日光節約時間';
usys67='自動調整到節約日光時區';
usys68='遠端管理:';    
AF='進階功能!';
usys69='遙控管理能讓您從網路上的任何地方更改路由器的設定，在您開啟此功能前';
usys70='請確認您已設定管理者密碼';
usys71='任何IP位址皆可被路由器遠端管理';  
usys72='只有此IP位址可被路由器遙控操作';  
usys73='NAT啟用:';    
usys74='能讓您關閉Network Address Translation功能，在大多數的狀況裡您最好不要將此功能關閉';
usys75='NAT啟用/關閉';
usys76='UPNP(通用隨插即播)開啟中: ';   
usys77='能讓您開啟或關閉UPNP功能。如果您使用此項功能來支援UPnP，開啟UPnP能讓這些應用程式自動安裝到路由器';
usys78='UPNP開啟/關閉';
usys79='開啟自動更新軔體:';  
usys80='讓您自動檢查路由器軔體更新';
usys81='自動更新軔體開啟/關閉';
usys82='現在使用的密碼是無效的';
usys83='新的密碼與更新後的密碼不同';
usys84='登入時間範圍1-99';
usys85='密碼長度不正確，最長3個數字，最短12個';
usys86='請手動更改狀態欄的位址輸入欄為預設lan位址';
usys87='我們強烈建議您設定管理者密碼';
usys88='Primary NTP Server';
usys89='Backup NTP Server';
usys90='192.43.244.18-North America';
usys91='132.163.4.102-North America';
usys92='192.5.41.41-North America';
usys93='192.5.41.209-North America';
usys94='207.200.81.113-North America';
usys95='208.184.49.9-North America';
usys96='129.132.2.21-Europe';
usys97='130.149.17.8-Europe';
usys98='137.189.8.174-Asia Pacific';
usys99='Remote Access Port';
usysipm='您可能未輸入所有的IP位址號碼或是部份您所輸入的號碼是不正確的。這些號碼應介於0到255 ';
usysb1='此路由器未設定任何密碼，如果您要提高安全性，您可在此輸入密碼';

vjs1='不正確的IP位址，IP位址過長，請再次確認';
vjs2='不正確的IP位址，少了xxx，請再次確認';
vjs3='不正確的IP位址，在XX之間少了一些號碼，請再次確認';
vjs4='不正確的IP位址，有多餘的.，請再次確認';
vjs5='不正確的IP位址，在XX之間的號碼過長，請再次確認';
vm1='不正確的字元';
vm2=' at Position ';
vm3='務必為';
vm4='不正確的號碼'; 
vjs6='不正確的年份格式，請輸入為(例如:2002)';
vjs8='不正確，必需介於1970..2037 ';
vjs9='不正確的月份格式，請輸入01...12';
vjs10='請先輸入年份與月份';
vjs11='不正確的日期格式，請輸入01...31，某些月份可能只有00..28';
vjs12='不正確的小時格式，請輸入00...23';
vjs13='不正確的分鐘格式，請輸入00…59';
vjs14='不正確的MTU值，其需介於1440…1454';
vjs15='不正確的MRU值，其需介於128…65535 ';
vjs16='不正確IP位址，';  vjs161="不在";   vjs162="網路遮罩";
vjs17='您輸入兩組不一樣的密碼，請再次確認!';
vjs18='請輸入開始連接埠的數值';
vjs19='開始連接埠的數值應小於最終連接埠的數值';
vjs20='不正確的連接埠數值，連接埠數值應為一正整數';
vjs21='不正確的長度';
vjs22='不正確的位置格式，';  vjs221='! 必須為:';
vjs23='不正確的媒體存取控制位址，其為一';
vjs24='不正確的媒體存取控制位址，其為零';
vjs25='不正確的媒體存取控制位址，其為廣播位址';
vjs26='不正確的開頭或末尾IP位址，末尾IP位址應大於開頭IP位址';
vjs27='不正確的號碼 必須介於1到65535';
vjs28='不正確的網路遮罩格式';
vjs29='不正確的格式，子網路遮罩應為255.255.255.0 或 255.255.255.128 或 255.255.255.192 或 255.255.255.224 或 255.255.255.240 或 255.255.255.248 或 255.255.255.252 或 255.255.255.254';
vjs30='不正確的IP位址，其最後一碼不能為0或255';
vjs31='不正確的區域網路IP位址，其第一碼不能為127';
vjs32='不正確的區域網路IP位址，其不能為0.0.0.0';
vjs33='不正確的區域網路IP位址，其必需低於224.0.0.0';
vjs34='正確的範圍是';
vjs35='此網頁已被個人控制台給鎖住';
vp1='此網站已被個人控制台阻擋住';
vp2='這已經被個人控制台禁止瀏覽並歸類為';
vp3='若您不認同此分級，並希望此網站被重新分級，請按不同意';
vp4='若您要修改個人控制台的規定，請按更改';
vp5='取消您的規定(僅限本台電腦)，請輸入密碼並選取取消';
Disagree='不同意';
Change='更改';
Override='取消';
wc1='廣域網路 > 連線類型';
wc2='選擇您的連線類型:'; 
wc3='動態IP'; 
wc4='動態類型的連線是最為普遍的。如果您使用纜線數據機，您較有可能是用動態連線。如果您有一個纜線數據機或您不確定你的連線類型，請使用這個';  
wc5='靜態'; 
wc6='一個靜態IP位址連線類型應較不為普遍。當您的網際網路服務供應商提供您一個永不改變的IP位址時您才使用這個選項'; 
wc7='PPPoE'; 
wc8='如果您使用DSL數據機或您的網際網路服務供應傷提供您一個使用者名稱與密碼，那麼您的連線類型就為PPPoE，請使用此種連線類型';  
wc9='PPTP'; 
wc10='[僅歐洲國家]　這種連線類型在歐洲國家最為普遍。如果您的網際網路服務供應商已告知您特別使用PPTP並已提供您正確的PPTP資訊，您可使用此選項'; 
wc11='Telstra BigPond'; 
wc12='[僅澳洲] Telstra BigPond使用者請使用此選項來連線'; 
Next='下一步';			
wds1='WAN > DNS';
wds2='如果您的網際網路服務供應商提供您一個特定的DNS位址，請在視窗中輸入請點選\"套用變更\"'; 
wds3='自動從網際網路服務供應商獲得 '; 
wds4='DNS位址';   
wds5='次級DNS位址';   
wds6='DNS意指網域名稱系統，是指一個位於網路上翻譯URL位址，例如www.belkin.com為一個IP位址';
wds7='如果您不始用自動DNS功能的話，您必須輸入網際網路服務供應商所提供的DNS設定';
wdy1='WAN > 連線類型 > 動態IP';
wdy2='輸入您的動態IP位址，請輸入以下資訊並選取"套用變更"';
wdy3='主機名稱';  
wdy4='主機名稱為一個網路服務供應商所';  
wdy5='更改WAN媒體存取控制位址 '; 
wdy6='不正確的主機名稱: ~!##$%^&*()=+{}[]|\'\\\":;?/.<> ';
wmc1='WAN > MAC位址';
wmc2='部份網際網路服務供應商只能讓您從網路卡上複製MAC位址到路由器。如果您不確定，只要複製在安裝路由器前原本連線到數據機的MAC位址。複製您的MAC位址不會造成任何問題';
wmc3='Wan Mac Address'; 
wmc4='複製電腦MAC位址';  
wmc5='複製';
wm1='網路/WAN';
WAN='廣域網路';
wm2='您可以在網路/廣域網路欄設定您的路由器來連接網路服務供應商。路由器能夠與任何網路服務供應商虛擬連線，只要您正確地能將路由器與網際網路服務供應商的設定連接。要將您的路由器與網際網路服務供應商連線，請按螢幕左邊的\"連線類型\"';
wm3='支援連線類型';
wm4='<b>動態IP:</b>包括要求一個主機名稱的網際網路服務供應商，其會連接至一個特定的媒體存取控制位址';
wm5='<b>靜態IP位址:</b> 路由器支援有指定靜態IP位址的ISP連線'; 
wm6='<b>PPPoE:</b> 乙太網路使用的點對點協定 路由器支援動態連線狀態，其將會要求PPPoE登入確認'; 
wm7='<b>PPTP:</b> 只限於歐洲用戶 路由器支援透過PPTP連線到歐洲網際網路服務供應商<br><br>';
wm8='<b>Telstra BigPond:</b>';
wm9='只限於澳洲用戶 路由器支援連線到Telstra BigPond '; 
wpe1=' WAN > 連線類型 > PPPoE ';
wpe2='輸入您的PPPoE設定，輸入您以下的資訊並選取\"套用變更\" ';
wpe3='使用者名稱';   
wpe4='重新輸入密碼';   
wpe5='服務名稱(可填可不填)';    
wpe6='MTU (1440-1454)';    
wpe7='請不要更改MTU值，除非您的網際網路服務供應商特別指定一個非1432的設定';
wpe8='斷線後';
wpe9='無活動分鐘數';
idlerangerro='您所輸入的閒置時間是不正確的。這個號碼可能介於1-99 ';
wpe10='不正確的字元符號 <>&';
pm='您的服務無法確認您所輸入的密碼。請確認您所輸入的密碼是正確的';
wpe11='不正確的MTU值';
wpe12='請輸入您的使用者名稱';
wpp1=' WAN > 連線類型 > PPTP ';
wpp2='PPTP帳號';
wpp3='PPTP密碼';
wpp4='請再次輸入密碼';
wpp5='主機名稱';
wpp6='服務IP位址';
wpp7='我的IP位址';
wpp8='我的子網路遮罩';
wpp9='連線ID(選用項目)';
wpp10='連線中斷之後';
wpp11='無活動分鐘數';
wpp12='請按此輸入您的DNS設定';
wpp13='請輸入您的PPTP帳號';
wpp14='請再次輸入密碼';
wpp15='請輸入您的密碼';
ws1='WNA > 連線類型 > 動態IP ';
ws2='輸入您的動態IP設定，請輸入以下資訊然後選取\"套用變更\"';
ws3='IP位址';
ws4='子網路遮罩';
ws5='ISP閘道位址';
ws6='我的網際網路服務供應商提供超過一個靜態IP位址? ';
ws7='按此輸入您的DNS設定';
dm='可能您尚未輸入所有的DNS號碼，或部份您所輸入的號碼不正確。此號碼應介於0到255';
sm='您所輸入的子網路遮罩號碼是不正確的';
ws8='請在接下來的視窗輸入您的DNS位址';
wsc1='IP位址別名'; 
im='IP位址別名列表已滿，無法增加更多'; 
wt1='WAN > 連線類型 > Telstra BigPond';
wt2='如果您的網路服務是由澳洲的Telstra BigPond所提供，您需要輸入以下的資訊。這些資訊由Telstra BigPond提供';
wt3='選取您的州';
wt4='使用者手動選取登入伺服器'; 
wt5='登入伺服器'; 
Logout='登出';
wt6='請輸入您的伺服器IP或從清單中選擇';
wla1='Wireless > Use as Access Point';
wlad1='路由器可以只限定用為一個無線基地台，只要將所有的。您可以選取"啟用"然後輸入您想要的IP位址即可';
wlad2='開啟/關閉';
wlae1='指定IP位址';  
wlae2='子網路遮罩';  
wlae3='請在您的瀏覽器中手動更改輸入欄的位址為區域網路的位址'; 
wlae4=	'1) 無線頻道必須與路由器與連接點相符<br>'+
		'2)安全設定(WEP)必須與路由器與連接點相符<br>'+
		'3)如果媒體存取控制防火牆開啟，使用者必須確定增加無線區域網路位址才能夠進行傳輸<br>';
wlc1='無線 > Channel與SSID ';
wlc2='要更改路由器上的無線設定，請在此更改，然後選取"套用變更"來儲存變更';
wlc3='無線頻道';
wlc4='SSID';  
wlc5='無線模式'; 
wlc6='54G-Auto';
wlc7='54G-Only';
wlc8='54G LRS';
wlc9='廣播SSID';  
wlc10='極速模式'; 
wlc11='選取"關閉"來關閉所有極速模式';
wlc12='保護模式';
wlc13="注意: 在大多數的情況中，最佳狀況(吞吐量)是將保護模式關閉。如果您使用HEAVY802.11b，最佳效能應為將保護模式關閉時";
wlc14='current channel';
wle1='無線 > 安全';
wle2='安全模式';
wle3='WPA-PSK(無伺服器)';
wle4='128位元WEP';
wle5='64位元WEP'; 
wle6='WPA (有Radius伺服器)';
wle7="您可以在此設定無線保全/加密。保全開啟時可確保最大值的無線保全。WPA提供的是不斷隨機改變的加密代碼以及指定出最佳的保全解決方案。在無線環境裡，並非所有的設備都能支援WPA，所以就必須使用WEP ";
wle8='(13個十六進位的成對數字)';  
wle9='注意: ';
wle10='若須使用PassPhrase產生成對的十六進位數字，按左邊的欄位並輸入PassPhrase';
PP='PassPhrase'; 
generate='產生';
errm='請輸入PassPhrase';
keym='金鑰不完整';
wle11='金鑰1';  
wle12='金鑰2'; 
wle13='金鑰3'; 
wle14='金鑰4';   
wle15='(十六進位的成對數字)'; 
wle16='WPA/WPA2(with Server)';
wle17='Advance Setting - Wireless Protected Access using a server to distribute keys to the clients: This option requires that a Radius server is running on the network.';
keym1='不完整';
keym2='不正確，請先修正!';
wlm1='無線';
wlm2='在這裡您可以調整設定為無線區';
wlm3='Channel與SSID ';
wlm4='調整無線頻道與SSID (無線網絡名稱) ';
wlm5='保全';
wlm6='更改無線保全設定，例如WPA設定或WEP設定';
wlm7='用來當做無線基地台';
wlm8='設定路由器的運作模式為AP模式';
wlm9='指定IP位址';
wlm10='指定AP的IP位址';
wlm11='媒體存取控制';
wlm12='設定一個您想要允許或是拒絕的無線網絡用戶清單';
wlm13='無線橋接器';
wlm14='讓您設定WDS bridging模式';
ww8='請輸入radius連接埠號碼';
ww9='Radius連接埠號碼應為一介於1至65535的號碼';
ww10='請輸入radius金鑰';
ww11='重新輸入間隔應為一個號碼';
ww12='重新輸入間隔應為大於60秒的時間 ';
ww1='WPA(跟伺服器)';
ww2='進階設定 - 無線保護存取使用伺服器來分配金鑰給用戶：這個選項需要Radius伺服器在網絡上運作';
ww3='加密技術';
ww4='Radius伺服器';
ww5='Radius連接埠';
ww6='Radius金鑰';
ww7='重新輸入間隔時間';
seconds='秒數';
wwp6='輸入PSK';
wwp7='PSK的長度應為8到63或64的十六進位數';
wwp1='預設值為TKIP';
wwp2='Pre-shared Key (PSK)';
wwp3='WPA-PSK(無伺服器)';
wwp4='此為一密碼，以單字、片語、一串字母或是數字所組成。這個密碼必須介於8和63個字母，其中可以包括空白或是標點符號。每一個連接到此網路的使用者必須要使用同一個密碼';
wwp5='Obscure PSK';
wlb1='無線 > 無線橋接器';
wlb2='無線或無線分部系統是用來連接無線路由器與無線基地台，可使網絡變廣大';
wlb3='開啟無線';
wlb4='開啟此功能會讓其他的Access Point可以連接到這個Access Point ';
wlb5='預設值開啟';
wlb6='僅開啟特定Access Point來連線';
wlb7="輸入無線基地台的無線媒體存取控制位址，如果這個項目沒有被確認，則任何基地台都可以連線。注意: 當連線到無線基地台，至少 提示:媒體存取控制可以透過無線用戶卡的網站尋找功能找到";
wlb8='關閉用戶無線連線功能';
wlb9='此功能只能在無線基地台用來連接其他無線路由器時';
wlb10='不正確'; 
wlbss1='Site Survey';
BSSID='BSSID';
wlbss2='網路類型';
wlbss3='加密';
wlbss4='選擇';
wlbss5='沒有找到可用的BSSID';
wlbss6='所有四個區域都滿了，請移除其中一個您才可以做新的選擇! ';
wlmc1='無線，媒體存取位址控制';
wlmc2='媒體存取位址控制 是設定一份您允許或拒絕存取無線網絡的用戶清單';
Allow='准許';   Deny='拒絕';   //Disable='使無效';
wlmc7='請先選擇您要允許或拒絕媒體存取控制位址清單';
wlmc6='無法輸入超過16個媒體存取控制位址';
wlmc3="不正確的媒體存取控制位址";
wlmc4='請先更正';
wlmc5='正確的媒體存取控制位址應為xx:xx:xx:xx:xx:xx而x是介於0-9與a-f';
ENTRY_FULL = '所有的輸入記錄已滿，請清除部份輸入記錄並再試一次';
CLEAR_CONFIRM='您要清除輸入記錄嗎?';
CLEAR_ALL_CONFIRM = '確認全部清除  您要清除所有輸入記錄嗎? ';
ERR_INTERNAL="內部錯誤，請確認Javascrip功能 -- "
			g1='IP位址是路由器的內部IP位址。存取進階設定介面，請在您的瀏覽器位址欄位中輸入此IP位址 如果有需要您可以更改這個位址，只要輸入新的位址然後選取\"應用更改\"，';
g2='192.168.x.x (x必須介於0跟255)<br>';
g3='10.x.x.x (x必須介於0跟255)<br>';
g4='172.y.x.x(y必須介於16到31，而x必須介於0跟255)<br>';
g5='無須改變子網路遮罩。如果需要的話可以更改子網路遮罩。僅在您有特殊理由時才更改子網路遮罩<br>'; 
g6='DNS是網域名稱系統伺服器的縮寫。一個網域名稱伺服器是一個位於URL位址的伺服器，例如:www.belkin.com。在您開始使用一個路由器前，許多網際網路服務供應商並不會要求您輸入這項資訊。當您的網際網路服務供應商不提供您一個特定的 DNS位址時，您應該要檢查\"自動由ISP獲取\"。如果您是使用靜態IP連線，您需要輸入一個特定的DNS位址，及一個次級的DNS位址。如果您的連線類型是是動態IP或PPPoE，您很有可能不一定需要輸入一個DNS位址。輸入DNS位址設定，自動從ISP獲取並輸入DNS，按\"應用更改\"來儲存設定。<br>';
g7='動態主機組態協定伺服器可以讓設定網路非常簡易，您只要替網絡中的每一個電腦指派一個IP位址。如果有需要您可以關閉DHCP伺服器。您需要替網絡中的每一台電腦手動設定一個靜態IP位址來關閉DHCP伺服器。IP位址的範圍應該，數值應介於2-100(99台電腦)，如果您要更改這個數字，您可以輸入一組新的開始與結束數字，然後選取\"應用更改值\" <br>';
g8='You can set a local domain name (network name) for your network. There is no need to change '+ 
 'this setting unless you have a specific advanced need to do so. You can name the network '+
 'anything you want such as \"MY NETWORK\". <br>';
g9='動態IP';
g10='動態連線是最多纜線數據機使用的連線類型。通常只要連線至ISP就可以將設定改為動態IP。有些動態連線可能會要求一個主機名稱，如果您有一個指定的主機名稱，將其輸入即可。您的主機名稱也是由您的ISP指定的，某些動態連線可能會要求您複製原本連接電腦的媒體存取控制位址。選取螢幕中的"更改廣域網路媒體存取控制位址"連結，如果您的路由器已正確連接，網路狀態顯示會"連線中"<br>';
g11='一個靜態IP位址連線類型較其他類型普遍。如果您的ISP使用靜態IP位址，您可能須要您的IP位址、子網路遮罩、與ISP閘道。您的ISP應提供相關資訊。輸入您的資料然後選取"應用"，在您應用這些改變後，如果您的路由器已正確設定，您的網路狀態會顯示為"連線中"。如果您的ISP提供您超過一個動態IP位址，您的路由器應可處理五個動態IP位址，選取"我的ISP提供超過一個的IP位址"然後輸入其他額外的IP位址<br>';
g12='大部份的數位用戶網路提供乙太網路的點對點協定。如果您使用纜線數據機來連接網路，您的網際網路服務供應商可能會使用乙太網路的點對點通訊協定來讓您登入網路。如果您的家用網路或小型辦公室連線不需要數據機，在以下的狀況您可以使用PPPoE: <br><br>'+
'1)  您的ISP提供您一個使用者名稱與密碼來進行連線<br>'+
'2)  您的ISP提供您網路連線的軟體，例如"WinPOET、Enternet300<br>'+
'3)  您必須確認選取桌面上的圖示來進行連線<br><br>' + 
'將路由器設定使用PPPoE，輸入您的使用者名稱與密碼，如果您沒有或您不知道，將該欄留空白即可。在您輸入所有資訊後選取"應用更改"，若您的路由器安裝正確，您的網路連線狀態將會顯示為\"連線中\"。若您需要更多資訊，請參閱使用手冊。<br>'; 
g13='有些網際網路服務供應商要求PPTP通訊協定。這將會使您可以直接設定一個ISP系統。輸入ISP提供的資訊，當您輸入完畢，選取\"套用變更\"。在您應用更新值後，如果您的路由器已正確連接，網路狀態顯示會\"連線中\"'; 
g14='您的使用者名稱與密碼是由Telstra BigPond提供。請輸入以下資訊，選取您的狀態且其會自動登入您的伺服器IP位址，如果您的登入伺服器位址跟提供的不同，您可能必需手動輸入登入伺服器IP位址，選取"套用變更"後，如果您的路由器已正確連接，網路狀態顯示會\"連線中\"';
g15='MTU設定';
g16='MTU設定值不會改變除非您的ISP提供您一個特定的MTU值。更改MTU值可以讓您解決以下問題: 從網路斷線、連線速度慢、網路應用作業問題'; 
			
g17='在X之後斷線…';
g18='斷線功能僅供在路由器從ISP自動斷線時使用，當一段時間無連線時。例如:當您使用的網路是以秒計費時，您可以使用此選項';
g19='MAC意指媒體存取控制。所有的網路零組件，包括網路卡、連接器以及路由器都有獨有的\"序號\"叫做媒體存取控制位址。您的網際網路服務供應商可能會記錄所有您的電腦的媒體存取控制位址，並且僅讓特定的電腦來使用網路服務。當您安裝路由器，路由器本身的MAC位址會被ISP查覺並造成網路無法作業。貝爾金已提供路由器電腦的MAC位址。如果您無法確定您的網際網路服務供應商是否需要檢查原本的MAC位址，只要複製MAC位址，並確保您所使用的電腦所連接的是在您安裝路由器前所使用的數據機。選取"複製MAC位址"再選取"套用變更，您的MAC位址即已被路由器複製';
g20='欲更改路由器的運作頻道，從選單下選取頻道，選取\"套用變更\"並儲存設定。您可以更改SSID。SSID是同等於無線網路的名稱。如果您所在的區域有其他的無線網路，您應該為其命名。預設值為belkin54g。欲更改SSID，選取SSID欄位並輸入一個新的名稱。選取"套用變更"使新的設定值生效'; 
g21='可以將您的無線網路設定為隱形。只要關閉SSID廣播。您的網絡就不會出現在XX。是一個由許多無線網路的連接器，他可以掃瞄空氣中所有可使用的網路並讓電腦可從中選擇。將SSID的廣播關閉可以提高安全性。';
g22='當您欲將路由器當做存取點時，您必須為其指定一個IP位址，此IP位址需落在您所連接的網路範圍內。欲進入路由器進階設定之介面，在網路瀏覽器輸入IP位址並登入';

g25='虛擬網路';
g26='此功能提供您路由至網路外部的服務，例如:網路伺服器(連接埠80)，FTP伺服器(連接埠21)，或其他透過您的路由器所能夠提供的服務。您的內部電腦被防火牆保護，所以在網路上並不會被\"看見\"。如果為了特定的應用程式，您需要使用虛擬伺服器組態，一般應用程式的清單將會被提供給您。如果您所需要的應用程式不在清單上，您必須聯絡您的應用程式賣主，了解您需要哪一種程式。若您要從提供的清單中選擇，從您所需要的應用程式那一行，然後選取\"進入\"。您的設定將會改變為您所指定的那一行。之後選取\"套用變更\"來儲存您更改的設定。若要手動設定更改，請輸入IP位址，連接埠(若有超過一個連接埠請在其間輸入逗號)，選取連接埠類型(TCP或UDP)然後選取\"套用變更\"';
g27='用戶IP防火牆';
g28='路由器可以設定在某些特定日期或特定時間無法連線到網路、電子郵件、或其他網路服務。這項設定可在一台電腦、一系列的電腦或是很多電腦。例如:您要限制某一台特定的電腦，輸入其IP位址與您欲限制的IP範圍。接下來在連接埠欄位輸入80，然後選擇TCP，接下來選擇Block。您也可以選擇永遠阻擋，在上方選擇開始日期與時間，然後在下方選擇結束日期與時間。選擇\"套用變更\"後，這台電腦在您所指定的時間就無法連線到你所指定的限制IP。注意:請確認您選擇正確的時區';
g29='媒體存取控制位址防火牆';
g30='媒體存取控制位址防火牆能夠讓您設定哪些電腦被允許連線。任何不被允許的電腦都將無法存取資訊。當您啟用這項功能，您必須在您網絡中的每一台電腦都輸入MAC位址，\"Block\"功能能讓您簡單地開啟或關閉網路存取功能，無需從清單上增加或移除MAC位址。欲使用這項功能，選取\"開啟媒體存取控制位址防火牆\"，接下來在每一台電腦輸入媒體存取控制防火牆位址，您只要選取\"增加\"，然後在空白欄位中輸入媒體存取控制防火牆，然後選擇\"套用變更\"即可。若要從清單上刪除媒體存取控制位址，只要在您欲刪除的媒體存取控制位址旁邊按\"刪除\"即可，然後選取\"套用變更\"。注意: 您所用來當做路由器管理員電腦，將無法刪除媒體存取控制功能。(指您現在所使用的電腦) ';
g31='非軍事區功能能讓您指定特定任一在您區域中的電腦被網路位址防火牆取代。如果網路位址發生問題，這項功能是必需的，由其當您使用電腦遊戲或是視訊會議時。若臨時狀況發生請使用此項功能。這台在非軍事區的電腦並未受到駭客攻擊的保護，將電腦放至非軍事區，輸入最後一個IP位址的數字，然後選取\"啟用\"，要讓更改生效請選取\"套用變更\"。若您要使用多個廣域網路IP位址，請選取非軍事區主機能夠直接連線的廣域網路IP位址，輸入非軍事區主機電腦IP位址的最後兩碼，點選\"啟用\"然後選取\"套用變更\"';
g32='阻擋ICMP Ping';
g33='電腦駭客通常會使用\"Pinging\"來尋找其欲攻擊的目標。透過偵測一個特定的IP位址並收到回應，電腦駭客可判斷出是否有利益的資訊可以截取。本路由器可以設定不給予外來的ICMP偵測回應，如此一來便可以提高您的電腦安全層級。要關閉電腦對Ping的回應，請選取\"阻擋ICMP Ping\"然後選取\"套用變更\"。';
g34='管理員密碼';
g35='本路由器並未設定任何密碼。若您要提高安全層級，你可以現在設定。請妥善保管您的密碼，未來您將需要此密碼來使用此路由器。若您要使用遙控管理功能，我們建議您最好設定密碼。<br><br>登出時間能讓您設定您能夠使用路由器進階設定的時間長度。當您開始閒置時，計時器會開始計時。例如:您已經在進階設定中做了更改，未點選"登出"就離開電腦，假設您設定登出時間為十分鐘，則在您離開電腦十分鐘之後，系統就會自動將您登出。這項功能是為了提高安全性，系統預設的登出時間為十分鐘。注意:在同一時間內只有一台電腦可以登入至進階設定的介面。';
g36='時間與時區';
g37='這台路由器的時間透過簡易網路時間通訊協定設定。如此可讓路由器與全球網路時間同步。路由器中的同步時鐘是用來記錄與控制使用者登入。請選擇你所居住地的時區。若您住在節約日光地區，則選擇\"啟用節約日光\"。系統可能不會馬上更新，請等候至少15分鐘讓路由器聯絡時區伺服器並得到回應，您無法自行設定時間。'; 
g38='遠端管理';
g39='在您啟用此項功能前，<font class="plaintext_bold">請確認您已經設定管理員密碼</font>。遠端管理能讓您從網路的任何地方做路由器的設定。總共有兩種遠端管理路由器的方式，第一種方式可以從任何地方存取路由器，只要選擇任何可以遙控管理路由器的IP位址。從網路上的任何地方輸入您廣域網路的IP，您可以看到一個要求您輸入路由器密碼的視窗。第二種方式能夠讓指定的IP位址被路由器遙控管理。這個方式比較安全，但是較為不便。若要使用這種方式，輸入您將要存取的路由器之IP位址，然後選擇\"只有這個IP位址可被路由器遠端操作\"。在您開啟此項功能前。我們強烈建議您設定一個管理者密碼。若讓密碼欄空白，很可能使您的路由器遭到入侵。';  
g40='開啟網路位址防火牆';
g41='在您啟用此項功能前，<font class="plaintext_bold">請確認您已經設定管理者密碼</font>。NAT可以讓您與網絡中的其他電腦分享ISP所提供的同一個IP位址。進階使用者應該僅使用此項功能。當您的ISP提供您多個IP位址，或是您需要進行進階系統組態而關閉NAT時，就需使用此項功能。如果您僅使用單一IP位址而您的NAT是關閉時，您的電腦將無法連線到網際網路。其他的問題也有可能會發生，將NAT關閉也將會關閉您的防火牆功能'; 
g42='UPnP (Universal Plug-and-Play) \"全球隨插即用\"提供無疏漏的作業，涵蓋了語音訊息、視訊訊息、遊戲及其他全球隨插即用的應用程式。某些應用程式需要路由器的防火牆透過特定的方式組態方能運作。通常會需要打開TCP與UDP的連接埠，有時還需要設定觸發程式連接埠。全球隨插即用可與路由器連線，它會告知路由器何處需要防火牆組態。此路由器的全球隨插即用功能是關閉的。如果您欲使用此功能，只要在工具程式頁面尋找\"啟用全球隨插即用\"然後選取\"啟用\"，再選取\"套用變更\"即可 ';
g43='自動軔體更新提醒';
g44='此路由器內建自動確認新版本的軔體並提醒您是否有新軔體可供更新。當您登入路由器的進階設定介面時，路由器會確認是否有新軔體可供更新。如果有，路由器會通知您。您可選擇下載新的軔體或是忽略該提示。此項功能設定為關閉，如果您要啟用，只要選取\"啟用\"，然後選取\"套用變更\"即可';
g45='無線安全';
g46='使用加密功能可讓您確保無線網路的安全層級。在同一時間內只能使用一種安全層級設定。所以使用者必須選擇能夠支援所有網絡裝置的模式。貝爾金產品共有五種安全層級設定可供您選擇:<br><br>'+
'1) 關閉。無開啟加密模式。所有網絡上的使用者皆可連線登入<br><br> '+ 
'2) WPA PSK - 家用(無伺服器)。無線保護存取是一種最近才所有的資訊包裝都有不同的加密代碼或是金鑰。如果金鑰持續改變，WPA仍然是安全的。總共有兩種WPA，一種是WPA-PSK (Pre-Shared Key)，另一種是WPA-Radius Server。兩者最顯著的差別在於一個需要伺服器一個不需要。WPA-PSK是提供沒有伺服器的家用或小型企業用戶。PSK加密金鑰是自動從。很明顯地，最大的危機在於當有人企圖從WPA PSK 找出您的Pass Phrase <br><br> '+ 
'a. TKIP(暫時金鑰完整性通訊協定)指AES(進階加密標準) WPA設定需要使用者選擇使用TKIP加密或AES加密。WPA標準指定TKIP，所以此為預設值。除此之外，TKIP應提供比賣主更佳的效能，因為有許多無線產品永遠無法升級為AES。AES是一種基於802.11i的最新加密技術。新的WPA標準將可能使用AES，雖然目前來說AES尚未普及，但是有些使用者較喜愛使用此科技。不管使用哪一種標準，所有的網路產品都一定要用一樣的技術<br><br> '+
'b. Pre-Shared Key 輸入一個超過40個字元的單字或片語，一樣PSK一定可以使用其他每一個在網絡中的無線網路設備。請注意上方和下方欄位的不同(大寫N跟小寫n是不一樣的)。最簡單破壞您網路安全的方式就是猜出您的PSK碼<br><br> '+ 
'3) 128-bit WEP 直到最近，128-bit WEP(Wired Equivalent Privacy)是無線加密的標準。如果不是您所有的無線配備支援WPA，128bitWEP仍可以提供極佳的安全選擇。系統會要求您輸入一個十六進位的數字，或您可以讓其自行產生<br><br> '+ 
'4) 64-bit WEP 貝爾金只建議64-bit模式，因為有些配備不支援WPA或128-bit WEP<br><br> '+ 
'5) WPA - Radius伺服器(此模式可透過進階按鈕存取)。WPA伺服器只能供網絡當做一個Radius伺服器來使用。所有的參數在此模式中都可以從Radius伺服器的管理員中獲得。不像是WPA PSK，WPA伺服器會提供伺服器一個金鑰而非讓系統自行產生<br> ';
g57='更新網域名稱';
fw1='軔體更新進行中';
fw2='請不要中斷或拔掉路由器的電源。如此做可能會導致其無法運作'; 
apply_text_1='Applying changes. Please wait....... ';

//------need to translate start-------
fd10='Dynamic DNS allows you to provide Internet users with a fixed domain name (instead of an IP address which may periodically change), allowing your router and applications set up in your router\'s virtual servers to be accessed from various locations on the Internet without knowing your current IP address. Your Wireless Router supports dynamic DNS through DynDNS.org';
um18=' of the Router.';
upc14=' subscribed to reporting.';
upad5='Default behavior when timeout occurs';
not='not';
ur4='Are you sure you want to restart the Router? Restarting the Router will not affect your configuration.';
ur5='Allow up to 60 seconds for the Router to restart. Do not power down the Router before reset completes.';
ww13='Authentication';
ww14='Advance Setting - Wireless Protected Access using a server to distribute keys to the clients: This option requires that a Radius server is running on the network.';
wwp5='Obscure PSK';
wlbss1='Site Survey';
usys89='Backup NTP Server';
usys90='192.43.244.18-North America';
usys91='132.163.4.102-North America';
usys92='192.5.41.41-North America';
usys93='192.5.41.209-North America';
usys94='207.200.81.113-North America';
usys95='208.184.49.9-North America';
usys96='129.132.2.21-Europe';
usys97='130.149.17.8-Europe';
usys98='137.189.8.174-Asia Pacific';
usys99='Remote Access Port';
vm2=' at Position ';
vjs161=" not in "; 
wla1='Wireless > Use as Access Point';
wmc3='Wan Mac Address'; 
wlm2='In this tab you can adjust settings to the Wireless section of the Router.';
g8='You can set a local domain name (network name) for your network. There is no need to change '+ 
 'this setting unless you have a specific advanced need to do so. You can name the network '+
 'anything you want such as \"MY NETWORK\". <br>';
g57='Using Dynamic DNS';
g58=' The Dynamic DNS service allows you to alias a dynamic IP address to a static host name in any of the many domains DynDNS.org offers, allowing your network computers to be more easily accessed from various locations on the Internet. DynDNS.org provides this service, for up to five host names, free to the Internet community.<br>'+
 'The Dynamic DNSSM service is ideal for a home website, file server, or to make it easy to access your home PC and stored files while you\'re at work. Using the service can ensure that your host name always points to your IP address, no matter how often your ISP changes it. When your IP address changes, your friends and associates can always locate you by visiting yourname.dyndns.org instead!<br>'+
 '<br>To register free for your Dynamic DNS host name, please visit http://www.dyndns.org.<br>'+
 '<br><b>Setting up the Router\'s Dynamic DNS Update Client</b><br>'+
 '<br>To register free for your Dynamic DNS host name, please visit http://www.dyndns.org.<br>'+
 '<br><b>Setting up the Router\'s Dynamic DNS Update Client</b><br>'+
 'You must register with DynDNS.org\'s free update service before using this feature. Once you have your registration, follow the directions below.<br>'+
 '1.Enter your DynDNS.org user name in the "User Name" field (1).<br>'+
 '2.Enter your DynDNS.org password in the "Password" field (2).<br>'+
 '3.Enter the DynDNS.org domain name you set up with DynDNS.org in the "Domain Name" field (3).<br>'+
 '4.Click "Update Dynamic DNS" to update your IP address.<br>'+
 'Whenever your IP address assigned by your ISP changes, the Router will automatically update DynDNS.org\'s servers with your new IP address. You can also do this manually by clicking the "Update Dynamic DNS" button (4).<br>';
wlq1='QoS (Quality of Service) Configuration';
wlq2='QoS prioritizes important data on your network such as multimedia content and voice-over-IP (VoIP) so it will not be interfered with by other data being sent over the network. Based on 802.11e, this feature can be turned on or off and you can choose the acknowledgement mode you want to use. If you plan to stream multimedia content or use VoIP on your network, the QoS feature should be enabled.<br>'; 
wlq3='QoS Switch'; 
wlq4='Allows you to turn ON or OFF QoS.<br>'; 
wlac1='ACK Mode'; 
wlac2=' There are two acknowledgement (ACK) modes that can be employed to get the best multimedia performance on your network: Burst ACK and Immediate ACK. <br><br>'+
 'Immediate ACK is the default (factory) setting and is recommended for normal network operation. Changing the ACK mode from Immediate ACK to Burst ACK may affect long-range throughput. Use Immediate ACK when long-range performance of your network is most important to you. <br><br>'+
 'Burst ACK mode will lower overhead by not acknowledging every packet sent over the network. When there is a very good link between the Router and the client, Burst ACK can provide a throughput boost. If an application, such as streaming multiple high-data video streams, requires maximum bandwidth, use Burst ACK mode. Keep in mind that long-range performance may be affected when using Burst ACK mode. <br>';
wmac1='Setting MAC Address Control'; 
wmac2=' The MAC address filter is a powerful security feature that allows you to specify which computers are allowed on the wireless network. Note: This list applies only to wireless computers. This list can be configured so any computer attempting to access the wireless network that is not specified in the filter list will be denied access. When you enable this feature, you must enter the MAC address of each client (computer) to which you want to allow network access. The "Block" feature lets you turn on and off access to the network easily for any computer without having to add and remove the computer\'s MAC address from the list.<br>'+
 'Setting up an Allow Access List <br>'+
 '1.Select the "Allow" radio button (1) to begin setting up a list of computers allowed to connect to the wireless network.<br>'+
 '2. Next, in the "MAC Address" field that is blank (3), type in the MAC address of the wireless computer you want to be able to access the wireless network, then click \"Add\" (4).<br>'+
 '3.Continue to do this until all of the computers you want to add have been entered.<br>'+
 '4. Click \"Apply Changes\" (5) to finish.<br><br>'+
 'Setting up a Deny Access List <br>'+
'The \"Deny Access\" list lets you specify computers that you DO NOT want to access the network. Any computer in the list will not be allowed access to the wireless network. All others will.<br>'+
 '1.Select the \"Deny\" radio button (2) to begin setting up a list of computers to be denied access to the wireless network.<br>'+
 '2. Next, in the \"MAC Address\" field that is blank (3), type in the MAC address of the wireless computer you want to deny access to the wireless network, then click "Add" (4).<br>'+
 '3. Continue to do this until all of the computers you want to deny access to have been entered.<br>'+
 '4. Click \"Apply Changes\" (5) to finish.<br>';
g23= 'Using the Wireless Mode Switch';
g24= 'This switch allows you to set the Router\'s wireless modes. There are three modes. <br>'+
'1) 802.11g only<br>'+
'Setting the Router to this mode will allow only Pre-N and 802.11g-compliant devices to join the network, keeping out any slower 802.11b devices.<br> '+
'2) 802.11g & 802.11b<br>'+
'Setting the Router to this mode will let Pre-N-, 802.11g-, and 802.11b-compliant devices to join the network. <br>'+
'3) Off<br>'+
'This mode will turn OFF the Router\'s access point, so no wireless devices can join the network. Turning off the wireless function of your Router is a great way to secure your network when you are away from home for a long period of time, or don\'t want to use the wireless feature of the Router at a certain time.';
apply_text_1='Applying changes. Please wait....... ';
warn_msg1='SSID can not be set as NULL!';
warn_msg2='The wireless will restart, if you are making this change from wireless computer, your wireless computer maybe temperorily disconnected from the router.';
//------need to translate end-------

//for print server main added by bin 02/04/2004
pm1='Print Service'
pm2='In this tab you can adjust settings to the Print Service section of the Print Server.'
pm3='Print Server Configuration'
pm4='Make adjustments to the Print Server Configuration.'
//for print server configuration added by bin 02/04/2004
pc1='Print Service > Print Server Configuration'
pc2='Print Server Name:'
pc3='Print Server Name >'
pc4='LPR Printing:'
pc5='This is always enabled. Belkin port uses LPR printing protocol.'
pc6='Raw TCP/IP Printing:'
pc7='Raw TCP/IP Printing protocol uses port 9100.'
pc8='Enable Raw TCP/IP Printing >'
pc9='FTP Printing:'
pc10='Print server accepts anonymous FTP to send file to printer'
pc11='Enable FTP Printing >'
pc12='No Printer connected'
pc13='Ready'
pc14='Out Of Paper'
pc15='Off Line'
pc16='Not Connected'
pc17='Printing'
pc18='Unknow Status'

parentalc_alert = 'Can not connect to outside'
parentalc_timeout = 'Timeout range: 1-60';
parentalc_alert_pwd = 'Password is incorrect'

g47='Printer Field';
g48='This line shows you the name of the printer that is connected to the router and the status of the printer.';
g49='Print Server Name';
g50='The print server name is used to identify the print server. The name can be changed to something more friendly if you prefer by typing in a new name such as "My Print Server" then clicking "Apply Changes"';
g51='LPR Printing (3)';
g52='The Belkin printer port uses LPR printing as the main method to print. ';
g53='Raw TCP/IP Printing';
g54='This feature allows clients to print to the Print Server using the standard TCP/IP printer port built into Windows XP and 2000 instead of the Belkin Port Monitor. Using Raw Printing requires the user to configure all port parameters manually and is not recommended for users unfamiliar with TCP/IP printing.';
g55='FTP Printing';
g56='This feature enables the printer to receive print jobs sent by FTP (see Using FTP Printing of the manual). Disabling this feature will prevent FTP jobs.';
h40='<b>USB Print Server</b> The USB print server in this router allows networked computer to print to a single USB printer. To enable a computer to print to this printer, you must install the printer\'s drivers and software on the computer and also you must install the Belkin printer port. The Belkin printer port software is included with the Router.';												
}
